Refactor scheduled workflows and improve health check

diff --git a/.github/workflows/scheduled-tasks.yml b/.github/workflows/scheduled-tasks.yml
--- a/.github/workflows/scheduled-tasks.yml
+++ b/.github/workflows/scheduled-tasks.yml
@@ -1,22 +1,36 @@
-name: scheduled workflows 
+name: Scheduled workflow
 
-on: 
+on:
   schedule:
-    - cron: '30 2 * * 1' #(every Monday at 2:30 AM UTC)
-    - cron: '0 */6 * * *' #(every 6 hours)
+    - cron: "30 2 * * 1" # every Monday at 2:30 AM UTC
+    - cron: "0 */6 * * *" # every 6 hours
   workflow_dispatch:
 
 jobs:
-  
-  scheduled:
+  scheduled-job:
     runs-on: ubuntu-latest
-
     steps:
+      - name: Checkout Code
+        uses: actions/checkout@v4
 
-      - name: schedule-print
-        run: echo "This schedule triggered :" ${{ github.event.schedule }}
-
-      - name: health check
+      - name: Print which schedule triggered 
         run: |
-          code=$(curl -s -o /dev/null -w "%{http_code}" www.google.com)
-          echo "Response code from wwww.google.com :" $code
+         if [ -z "${{ github.event.schedule }}" ]; then
+            echo "Workflow triggered manually"
+         else
+            echo "Workflow triggered by cron schedule: ${{ github.event.schedule }}"
+         fi
+
+      - name: Health Check
+        run: |
+          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://www.trainwithshubham.com/)
+          echo "HTTP Status: $STATUS"
+          if [ "$STATUS" -ne 200 ]; then
+            echo "Health check failed!"
+          exit 1
+          fi
+
+
+# -s silent mode, hides progress and error messages
+# -o /dev/null → discard the page content, don’t print HTML
+# -w "%{http_code}" → print only the HTTP status code (like 200, 404, etc.)
